version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Use the version of Node.js installed on Elastic Beanstalk
    commands:
      - npm install

artifacts:
  files:
    - '**/*'
